// AUTO-GENERATED by docs-site/scripts/generate-pages.ts — do not edit by hand.
export type Control = { name: string; required?: boolean } & (
  | { kind: 'enum'; options: string[]; def?: string }
  | { kind: 'boolean'; def?: boolean }
  | { kind: 'number'; def?: number }
  | { kind: 'text'; def?: string }
);

export const controlsByName: Record<string, Control[]> = {
  Button: [
    {
      name: 'variant',
      kind: 'enum',
      options: ['solid', 'outline', 'ghost'],
      def: 'solid',
    },
    {
      name: 'tone',
      kind: 'enum',
      options: ['primary', 'neutral', 'success', 'warning', 'danger', 'info', 'accent'],
      def: 'primary',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'fullWidth',
      kind: 'boolean',
    },
  ],
  LoadingButton: [
    {
      name: 'loading',
      kind: 'boolean',
    },
    {
      name: 'loadingText',
      kind: 'text',
    },
  ],
  ButtonGroup: [
    {
      name: 'orientation',
      kind: 'enum',
      options: ['horizontal', 'vertical'],
      def: 'horizontal',
    },
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
  ],
  SplitButton: [
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
    {
      name: 'menuLabel',
      kind: 'text',
      def: 'More actions',
    },
  ],
  ToggleGroup: [
    {
      name: 'type',
      kind: 'enum',
      options: ['single', 'multiple'],
      def: 'single',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'tone',
      kind: 'enum',
      options: ['primary', 'neutral', 'success', 'warning', 'danger', 'info', 'accent'],
      def: 'primary',
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
    {
      name: 'orientation',
      kind: 'enum',
      options: ['horizontal', 'vertical'],
      def: 'horizontal',
    },
  ],
  TextField: [
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'value',
      kind: 'text',
    },
    {
      name: 'defaultValue',
      kind: 'text',
    },
    {
      name: 'helperText',
      kind: 'text',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
    {
      name: 'errorText',
      kind: 'text',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'density',
      kind: 'enum',
      options: ['comfortable', 'compact'],
      def: 'comfortable); set explicitly to set `data-density`',
    },
    {
      name: 'startAdornment',
      kind: 'text',
    },
    {
      name: 'endAdornment',
      kind: 'text',
    },
  ],
  PasswordInput: [
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'value',
      kind: 'text',
    },
    {
      name: 'defaultValue',
      kind: 'text',
    },
    {
      name: 'helperText',
      kind: 'text',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
    {
      name: 'errorText',
      kind: 'text',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'density',
      kind: 'enum',
      options: ['comfortable', 'compact'],
    },
  ],
  Textarea: [
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'value',
      kind: 'text',
    },
    {
      name: 'defaultValue',
      kind: 'text',
    },
    {
      name: 'helperText',
      kind: 'text',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
    {
      name: 'errorText',
      kind: 'text',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'autoResize',
      kind: 'boolean',
    },
    {
      name: 'minRows',
      kind: 'number',
    },
    {
      name: 'maxRows',
      kind: 'number',
    },
  ],
  NumberField: [
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'value',
      kind: 'number',
    },
    {
      name: 'defaultValue',
      kind: 'number',
    },
    {
      name: 'min',
      kind: 'number',
    },
    {
      name: 'max',
      kind: 'number',
    },
    {
      name: 'step',
      kind: 'number',
      def: 1,
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'required',
      kind: 'boolean',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
    {
      name: 'helperText',
      kind: 'text',
    },
    {
      name: 'errorText',
      kind: 'text',
    },
  ],
  PinInput: [
    {
      name: 'length',
      kind: 'number',
      def: 6,
    },
    {
      name: 'value',
      kind: 'text',
    },
    {
      name: 'defaultValue',
      kind: 'text',
    },
    {
      name: 'type',
      kind: 'enum',
      options: ['number', 'text'],
      def: 'number',
    },
    {
      name: 'mask',
      kind: 'boolean',
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: "'aria-label'",
      kind: 'text',
    },
  ],
  Checkbox: [
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'checked',
      kind: 'boolean',
    },
    {
      name: 'defaultChecked',
      kind: 'boolean',
    },
    {
      name: 'indeterminate',
      kind: 'boolean',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
  ],
  Radio: [
    {
      name: 'value',
      kind: 'text',
      required: true,
    },
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
  ],
  Switch: [
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'checked',
      kind: 'boolean',
    },
    {
      name: 'defaultChecked',
      kind: 'boolean',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
  ],
  TagInput: [
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'placeholder',
      kind: 'text',
    },
    {
      name: 'max',
      kind: 'number',
    },
    {
      name: 'allowDuplicates',
      kind: 'boolean',
      def: false,
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md'],
    },
    {
      name: 'name',
      kind: 'text',
    },
    {
      name: 'required',
      kind: 'boolean',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
    {
      name: 'helperText',
      kind: 'text',
    },
    {
      name: 'errorText',
      kind: 'text',
    },
  ],
  Slider: [
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'value',
      kind: 'number',
    },
    {
      name: 'defaultValue',
      kind: 'number',
    },
    {
      name: 'min',
      kind: 'number',
    },
    {
      name: 'max',
      kind: 'number',
    },
    {
      name: 'step',
      kind: 'number',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md'],
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
    {
      name: 'helperText',
      kind: 'text',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
    {
      name: 'errorText',
      kind: 'text',
    },
  ],
  Rating: [
    {
      name: 'value',
      kind: 'number',
    },
    {
      name: 'defaultValue',
      kind: 'number',
      def: 0,
    },
    {
      name: 'max',
      kind: 'number',
      def: 5,
    },
    {
      name: 'readOnly',
      kind: 'boolean',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: "'aria-label'",
      kind: 'text',
    },
  ],
  FileUpload: [
    {
      name: 'accept',
      kind: 'text',
    },
    {
      name: 'multiple',
      kind: 'boolean',
      def: false,
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
    {
      name: 'label',
      kind: 'text',
      def: 'a sensible string',
    },
  ],
  ColorPicker: [
    {
      name: 'value',
      kind: 'text',
    },
    {
      name: 'defaultValue',
      kind: 'text',
      def: '#1B5FCC',
    },
    {
      name: 'alpha',
      kind: 'boolean',
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
    {
      name: 'label',
      kind: 'text',
    },
  ],
  DatePicker: [
    {
      name: 'granularity',
      kind: 'enum',
      options: ['day', 'minute'],
    },
    {
      name: 'withSeconds',
      kind: 'boolean',
    },
    {
      name: 'minuteStep',
      kind: 'number',
    },
    {
      name: 'placeholder',
      kind: 'text',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
    {
      name: 'required',
      kind: 'boolean',
    },
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'locale',
      kind: 'text',
    },
  ],
  DateRangePicker: [
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
    {
      name: 'required',
      kind: 'boolean',
    },
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'startPlaceholder',
      kind: 'text',
      def: '`dateRangePicker',
    },
    {
      name: 'endPlaceholder',
      kind: 'text',
      def: '`dateRangePicker',
    },
    {
      name: 'startLabel',
      kind: 'text',
      def: '`dateRangePicker',
    },
    {
      name: 'endLabel',
      kind: 'text',
      def: '`dateRangePicker',
    },
    {
      name: 'locale',
      kind: 'text',
    },
  ],
  TimePicker: [
    {
      name: 'withSeconds',
      kind: 'boolean',
      def: false,
    },
    {
      name: 'minuteStep',
      kind: 'number',
      def: 1,
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
    {
      name: 'required',
      kind: 'boolean',
    },
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'helperText',
      kind: 'text',
    },
    {
      name: 'errorText',
      kind: 'text',
    },
    {
      name: 'locale',
      kind: 'text',
    },
  ],
  FormField: [
    {
      name: 'label',
      kind: 'text',
      required: true,
    },
    {
      name: 'name',
      kind: 'text',
    },
    {
      name: 'required',
      kind: 'boolean',
    },
    {
      name: 'error',
      kind: 'boolean',
    },
    {
      name: 'errorText',
      kind: 'text',
    },
    {
      name: 'helperText',
      kind: 'text',
    },
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
  ],
  Chip: [
    {
      name: 'label',
      kind: 'text',
      required: true,
    },
    {
      name: 'variant',
      kind: 'enum',
      options: ['solid', 'outline'],
      def: 'solid',
    },
    {
      name: 'tone',
      kind: 'enum',
      options: ['primary', 'neutral', 'success', 'warning', 'danger', 'info', 'accent'],
      def: 'neutral',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md'],
      def: 'md',
    },
  ],
  Avatar: [
    {
      name: 'src',
      kind: 'text',
    },
    {
      name: 'alt',
      kind: 'text',
    },
    {
      name: 'name',
      kind: 'text',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'shape',
      kind: 'enum',
      options: ['circle', 'square'],
      def: 'circle',
    },
  ],
  AvatarGroup: [
    {
      name: 'max',
      kind: 'number',
    },
    {
      name: 'total',
      kind: 'number',
    },
    {
      name: 'spacing',
      kind: 'enum',
      options: ['tight', 'normal'],
      def: 'normal',
    },
    {
      name: 'label',
      kind: 'text',
    },
  ],
  StatusBadge: [
    {
      name: 'status',
      kind: 'enum',
      options: ['active', 'inactive', 'pending', 'error'],
      required: true,
    },
    {
      name: 'label',
      kind: 'text',
      required: true,
    },
    {
      name: 'variant',
      kind: 'enum',
      options: ['solid', 'subtle'],
      def: 'subtle',
    },
  ],
  NotificationBadge: [
    {
      name: 'children',
      kind: 'text',
    },
    {
      name: 'count',
      kind: 'number',
    },
    {
      name: 'max',
      kind: 'number',
      def: 99,
    },
    {
      name: 'dot',
      kind: 'boolean',
    },
    {
      name: 'showZero',
      kind: 'boolean',
      def: false,
    },
    {
      name: 'placement',
      kind: 'enum',
      options: ['top-end', 'top-start', 'bottom-end', 'bottom-start'],
      def: 'top-end',
    },
    {
      name: 'label',
      kind: 'text',
    },
  ],
  Alert: [
    {
      name: 'severity',
      kind: 'enum',
      options: ['info', 'success', 'warning', 'error'],
      required: true,
    },
    {
      name: 'title',
      kind: 'text',
    },
    {
      name: 'dismissable',
      kind: 'boolean',
    },
  ],
  Banner: [
    {
      name: 'severity',
      kind: 'enum',
      options: ['info', 'success', 'warning', 'error'],
      required: true,
    },
    {
      name: 'title',
      kind: 'text',
    },
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
    {
      name: 'dismissable',
      kind: 'boolean',
    },
    {
      name: 'action',
      kind: 'text',
    },
  ],
  Card: [
    {
      name: 'variant',
      kind: 'enum',
      options: ['outline', 'elevated', 'flat'],
      def: 'outline',
    },
    {
      name: 'padding',
      kind: 'enum',
      options: ['none', 'sm', 'md', 'lg'],
      def: 'md',
    },
  ],
  EmptyState: [
    {
      name: 'title',
      kind: 'text',
      required: true,
    },
    {
      name: 'description',
      kind: 'text',
    },
    {
      name: 'action',
      kind: 'text',
    },
  ],
  Progress: [
    {
      name: 'value',
      kind: 'number',
    },
    {
      name: 'max',
      kind: 'number',
    },
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'showValue',
      kind: 'boolean',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
    },
    {
      name: 'tone',
      kind: 'enum',
      options: ['primary', 'neutral', 'success', 'warning', 'danger', 'info', 'accent'],
    },
  ],
  Meter: [
    {
      name: 'value',
      kind: 'number',
      required: true,
    },
    {
      name: 'min',
      kind: 'number',
    },
    {
      name: 'max',
      kind: 'number',
    },
    {
      name: 'low',
      kind: 'number',
    },
    {
      name: 'high',
      kind: 'number',
    },
    {
      name: 'optimum',
      kind: 'number',
    },
    {
      name: 'label',
      kind: 'text',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md'],
    },
    {
      name: 'showValue',
      kind: 'boolean',
    },
  ],
  Spinner: [
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'tone',
      kind: 'enum',
      options: ['primary', 'neutral'],
      def: 'primary',
    },
    {
      name: 'label',
      kind: 'text',
    },
  ],
  Skeleton: [
    {
      name: 'variant',
      kind: 'enum',
      options: ['text', 'rect', 'circle'],
      def: 'text',
    },
    {
      name: 'animation',
      kind: 'enum',
      options: ['pulse', 'none'],
      def: 'pulse',
    },
  ],
  Stat: [
    {
      name: 'label',
      kind: 'text',
      required: true,
    },
    {
      name: 'value',
      kind: 'text',
      required: true,
    },
    {
      name: 'delta',
      kind: 'text',
    },
    {
      name: 'trend',
      kind: 'enum',
      options: ['up', 'down', 'neutral'],
      def: 'neutral',
    },
    {
      name: 'helpText',
      kind: 'text',
    },
  ],
  CountUp: [
    {
      name: 'value',
      kind: 'number',
      required: true,
    },
    {
      name: 'from',
      kind: 'number',
      def: 0,
    },
    {
      name: 'duration',
      kind: 'number',
      def: 800,
    },
    {
      name: 'decimals',
      kind: 'number',
      def: 0,
    },
  ],
  Sparkline: [
    {
      name: 'type',
      kind: 'enum',
      options: ['line', 'area', 'bar'],
      def: 'line',
    },
    {
      name: 'width',
      kind: 'number',
      def: 120,
    },
    {
      name: 'height',
      kind: 'number',
      def: 32,
    },
    {
      name: 'color',
      kind: 'text',
      def: 'the first categorical chart color',
    },
    {
      name: "'aria-label'",
      kind: 'text',
    },
  ],
  Chart: [
    {
      name: 'type',
      kind: 'enum',
      options: ['line', 'bar'],
      def: 'line',
    },
    {
      name: 'width',
      kind: 'number',
      def: 320,
    },
    {
      name: 'height',
      kind: 'number',
      def: 180,
    },
    {
      name: 'showAxes',
      kind: 'boolean',
      def: true,
    },
    {
      name: "'aria-label'",
      kind: 'text',
    },
  ],
  Table: [
    {
      name: 'caption',
      kind: 'text',
    },
    {
      name: 'captionVisible',
      kind: 'boolean',
      def: false,
    },
    {
      name: 'sortKey',
      kind: 'text',
    },
    {
      name: 'sortDir',
      kind: 'enum',
      options: ['asc', 'desc'],
    },
    {
      name: 'loading',
      kind: 'boolean',
    },
    {
      name: 'loadingRows',
      kind: 'number',
    },
    {
      name: 'empty',
      kind: 'text',
    },
    {
      name: 'stickyHeader',
      kind: 'boolean',
    },
    {
      name: 'density',
      kind: 'enum',
      options: ['comfortable', 'compact'],
      def: 'comfortable)',
    },
  ],
  DescriptionList: [
    {
      name: 'termWidth',
      kind: 'text',
      def: 'max-content',
    },
  ],
  Tree: [
    {
      name: 'defaultSelectedId',
      kind: 'text',
    },
    {
      name: 'selectedId',
      kind: 'text',
    },
  ],
  Code: [
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
  ],
  Kbd: [
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md'],
      def: 'md',
    },
  ],
  Dialog: [
    {
      name: 'open',
      kind: 'boolean',
      required: true,
    },
    {
      name: 'title',
      kind: 'text',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'dismissable',
      kind: 'boolean',
    },
    {
      name: 'footer',
      kind: 'text',
    },
    {
      name: 'children',
      kind: 'text',
    },
  ],
  Drawer: [
    {
      name: 'open',
      kind: 'boolean',
      required: true,
    },
    {
      name: 'title',
      kind: 'text',
    },
    {
      name: 'side',
      kind: 'enum',
      options: ['start', 'end', 'top', 'bottom'],
      def: 'end',
    },
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg'],
      def: 'md',
    },
    {
      name: 'dismissable',
      kind: 'boolean',
    },
    {
      name: 'footer',
      kind: 'text',
    },
    {
      name: 'children',
      kind: 'text',
    },
  ],
  Snackbar: [
    {
      name: 'open',
      kind: 'boolean',
      required: true,
    },
    {
      name: 'severity',
      kind: 'enum',
      options: ['info', 'success', 'warning', 'error'],
      def: 'info',
    },
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
    {
      name: 'action',
      kind: 'text',
    },
    {
      name: 'autoHideDuration',
      kind: 'number',
    },
    {
      name: 'placement',
      kind: 'enum',
      options: ['bottom-center', 'bottom-left', 'bottom-right', 'top-center'],
      def: 'bottom-center',
    },
  ],
  Toaster: [
    {
      name: 'max',
      kind: 'number',
      def: 3,
    },
  ],
  Popover: [
    {
      name: 'open',
      kind: 'boolean',
    },
    {
      name: 'defaultOpen',
      kind: 'boolean',
    },
    {
      name: 'placement',
      kind: 'enum',
      options: [
        'top',
        'top-start',
        'top-end',
        'bottom',
        'bottom-start',
        'bottom-end',
        'left',
        'left-start',
        'left-end',
        'right',
        'right-start',
        'right-end',
      ],
      def: 'bottom',
    },
    {
      name: 'offset',
      kind: 'number',
      def: 8,
    },
    {
      name: 'dismissable',
      kind: 'boolean',
    },
    {
      name: 'role',
      kind: 'text',
    },
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
  ],
  Popconfirm: [
    {
      name: 'title',
      kind: 'text',
    },
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
    {
      name: 'confirmLabel',
      kind: 'text',
      def: 'Confirm',
    },
    {
      name: 'cancelLabel',
      kind: 'text',
      def: 'Cancel',
    },
    {
      name: 'open',
      kind: 'boolean',
    },
  ],
  HoverCard: [
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
    {
      name: 'openDelay',
      kind: 'number',
      def: 300,
    },
    {
      name: 'closeDelay',
      kind: 'number',
      def: 150,
    },
  ],
  Tooltip: [
    {
      name: 'content',
      kind: 'text',
      required: true,
    },
    {
      name: 'delay',
      kind: 'number',
      def: 200,
    },
  ],
  Menu: [
    {
      name: 'density',
      kind: 'enum',
      options: ['comfortable', 'compact'],
      def: 'comfortable); set\nexplicitly to set `data-density` on the menu list',
    },
  ],
  CommandPalette: [
    {
      name: 'open',
      kind: 'boolean',
      required: true,
    },
    {
      name: 'placeholder',
      kind: 'text',
      def: 'Type a command or search…',
    },
    {
      name: 'noResultsText',
      kind: 'text',
      def: 'No results',
    },
    {
      name: "'aria-label'",
      kind: 'text',
      def: 'Command menu',
    },
  ],
  AppBar: [
    {
      name: 'logo',
      kind: 'text',
    },
    {
      name: 'title',
      kind: 'text',
    },
    {
      name: 'actions',
      kind: 'text',
    },
    {
      name: 'position',
      kind: 'enum',
      options: ['static', 'sticky'],
      def: 'static',
    },
    {
      name: 'elevation',
      kind: 'boolean',
      def: true,
    },
  ],
  Sidebar: [
    {
      name: 'collapsed',
      kind: 'boolean',
    },
    {
      name: 'defaultCollapsed',
      kind: 'boolean',
      def: false,
    },
    {
      name: 'header',
      kind: 'text',
    },
    {
      name: 'footer',
      kind: 'text',
    },
  ],
  Breadcrumbs: [
    {
      name: 'separator',
      kind: 'text',
      def: 'a chevron icon',
    },
    {
      name: 'maxItems',
      kind: 'number',
    },
  ],
  Tabs: [
    {
      name: 'value',
      kind: 'text',
    },
    {
      name: 'defaultValue',
      kind: 'text',
      def: 'the first non-disabled item',
    },
    {
      name: 'orientation',
      kind: 'enum',
      options: ['horizontal', 'vertical'],
      def: 'horizontal',
    },
    {
      name: 'lazy',
      kind: 'boolean',
      def: false,
    },
    {
      name: 'keepMounted',
      kind: 'boolean',
      def: false,
    },
  ],
  Pagination: [
    {
      name: 'count',
      kind: 'number',
      required: true,
    },
    {
      name: 'page',
      kind: 'number',
      required: true,
    },
    {
      name: 'siblingCount',
      kind: 'number',
    },
    {
      name: 'boundaryCount',
      kind: 'number',
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
    {
      name: 'previousLabel',
      kind: 'text',
      def: "the i18n catalog's `pagination",
    },
    {
      name: 'nextLabel',
      kind: 'text',
      def: "the i18n catalog's `pagination",
    },
  ],
  Stepper: [
    {
      name: 'activeStep',
      kind: 'number',
      required: true,
    },
    {
      name: 'orientation',
      kind: 'enum',
      options: ['horizontal', 'vertical'],
      def: 'horizontal',
    },
  ],
  PageHeader: [
    {
      name: 'title',
      kind: 'text',
      required: true,
    },
    {
      name: 'subtitle',
      kind: 'text',
    },
    {
      name: 'actions',
      kind: 'text',
    },
  ],
  Link: [
    {
      name: 'tone',
      kind: 'enum',
      options: ['primary', 'neutral'],
      def: 'primary',
    },
    {
      name: 'underline',
      kind: 'enum',
      options: ['always', 'hover', 'none'],
      def: "always' so links embedded in body\ntext stay distinguishable without relying on color (WCAG 1",
    },
  ],
  Stack: [
    {
      name: 'align',
      kind: 'enum',
      options: ['start', 'center', 'end', 'stretch', 'baseline'],
    },
    {
      name: 'justify',
      kind: 'enum',
      options: ['start', 'center', 'end', 'between', 'around'],
    },
    {
      name: 'wrap',
      kind: 'boolean',
    },
  ],
  Inline: [
    {
      name: 'align',
      kind: 'enum',
      options: ['start', 'center', 'end', 'stretch', 'baseline'],
    },
    {
      name: 'justify',
      kind: 'enum',
      options: ['start', 'center', 'end', 'between', 'around'],
    },
    {
      name: 'wrap',
      kind: 'boolean',
    },
  ],
  Container: [
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg', 'xl'],
      def: 'lg',
    },
    {
      name: 'padded',
      kind: 'boolean',
      def: true,
    },
  ],
  Box: [
    {
      name: 'grow',
      kind: 'boolean',
    },
    {
      name: 'shrink',
      kind: 'boolean',
    },
    {
      name: 'width',
      kind: 'text',
    },
  ],
  Accordion: [
    {
      name: 'multiple',
      kind: 'boolean',
      def: false,
    },
    {
      name: 'collapsible',
      kind: 'boolean',
      def: true,
    },
    {
      name: 'lazy',
      kind: 'boolean',
      def: false,
    },
    {
      name: 'keepMounted',
      kind: 'boolean',
      def: false,
    },
  ],
  Collapsible: [
    {
      name: 'trigger',
      kind: 'text',
      required: true,
    },
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
    {
      name: 'open',
      kind: 'boolean',
    },
    {
      name: 'defaultOpen',
      kind: 'boolean',
      def: false,
    },
    {
      name: 'disabled',
      kind: 'boolean',
    },
  ],
  ScrollArea: [
    {
      name: 'children',
      kind: 'text',
      required: true,
    },
    {
      name: 'orientation',
      kind: 'enum',
      options: ['vertical', 'horizontal', 'both'],
      def: 'vertical',
    },
  ],
  Carousel: [
    {
      name: 'defaultIndex',
      kind: 'number',
      def: 0,
    },
    {
      name: 'index',
      kind: 'number',
    },
    {
      name: 'loop',
      kind: 'boolean',
      def: false,
    },
    {
      name: "'aria-label'",
      kind: 'text',
    },
    {
      name: 'prevLabel',
      kind: 'text',
      def: "the i18n catalog ('Previous slide')",
    },
    {
      name: 'nextLabel',
      kind: 'text',
      def: "the i18n catalog ('Next slide')",
    },
  ],
  AspectRatio: [
    {
      name: 'ratio',
      kind: 'number',
    },
    {
      name: 'children',
      kind: 'text',
    },
  ],
  Divider: [
    {
      name: 'orientation',
      kind: 'enum',
      options: ['horizontal', 'vertical'],
      def: 'horizontal',
    },
    {
      name: 'children',
      kind: 'text',
    },
    {
      name: 'inset',
      kind: 'boolean',
    },
  ],
  Text: [
    {
      name: 'size',
      kind: 'enum',
      options: ['xs', 'sm', 'md', 'lg', 'xl', '2xl'],
    },
    {
      name: 'weight',
      kind: 'enum',
      options: ['regular', 'medium', 'semibold', 'bold'],
    },
    {
      name: 'tone',
      kind: 'enum',
      options: ['default', 'secondary'],
    },
    {
      name: 'leading',
      kind: 'enum',
      options: ['tight', 'normal', 'relaxed'],
    },
    {
      name: 'family',
      kind: 'enum',
      options: ['base', 'mono'],
    },
    {
      name: 'numeric',
      kind: 'enum',
      options: ['normal', 'tabular'],
    },
    {
      name: 'transform',
      kind: 'enum',
      options: ['none', 'uppercase', 'lowercase', 'capitalize'],
    },
    {
      name: 'truncate',
      kind: 'boolean',
    },
    {
      name: 'lineClamp',
      kind: 'number',
    },
  ],
  Heading: [
    {
      name: 'size',
      kind: 'enum',
      options: ['sm', 'md', 'lg', 'xl', '2xl'],
    },
    {
      name: 'weight',
      kind: 'enum',
      options: ['regular', 'medium', 'semibold', 'bold'],
    },
    {
      name: 'leading',
      kind: 'enum',
      options: ['tight', 'normal', 'relaxed'],
      def: "`'tight'`",
    },
  ],
};
