import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tokens, themes, density } from '../src/theme/tokens';

const camelToKebab = (s: string) =>
  s
    // camelCase boundary: lower/digit → Upper (bgDefault → bg-default)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    // letter → digit boundary: keeps numbered scales readable (chart1 → chart-1)
    .replace(/([a-zA-Z])([0-9])/g, '$1-$2')
    .toLowerCase();

function scaleVars(): string {
  const lines: string[] = [];
  for (const [scaleName, scale] of Object.entries(tokens)) {
    for (const [key, value] of Object.entries(scale)) {
      lines.push(`  --ku-${camelToKebab(scaleName)}-${camelToKebab(String(key))}: ${value};`);
    }
  }
  return lines.join('\n');
}

function colorVars(mode: 'dark' | 'light'): string {
  return Object.entries(themes[mode].color)
    .map(([name, value]) => `  --ku-color-${camelToKebab(name)}: ${value};`)
    .join('\n');
}

// Density-aware spacing vars. `comfortable` is the default (emitted on :root with
// the scale/color vars); `compact` overrides the same `--ku-density-*` names under
// `[data-density='compact']`. Components read these for internal padding/row-height.
function densityVars(mode: 'comfortable' | 'compact'): string {
  return Object.entries(density[mode])
    .map(([name, value]) => `  --ku-density-${camelToKebab(name)}: ${value};`)
    .join('\n');
}

export function buildThemeCss(): string {
  return [
    '/* AUTO-GENERATED by scripts/generate-theme-css.ts — do not edit by hand. */',
    `:root {\n${scaleVars()}\n${colorVars('dark')}\n${densityVars('comfortable')}\n}`,
    // Theme overrides respond to BOTH strategies: the `data-theme` attribute
    // (set by KoduhThemeProvider) AND a `.dark` / `.light` class — the latter so
    // Tailwind consumers using `darkMode: 'class'` get our tokens for free. Note
    // :root above is dark-by-default; a class-strategy app whose light state is
    // "no class" must toggle `.light` explicitly to reach the light palette.
    `:root[data-theme='dark'], [data-theme="dark"], :root.dark, .dark {\n${colorVars('dark')}\n}`,
    `:root[data-theme='light'], [data-theme="light"], :root.light, .light {\n${colorVars('light')}\n}`,
    `[data-density='comfortable'] {\n${densityVars('comfortable')}\n}`,
    `[data-density='compact'] {\n${densityVars('compact')}\n}`,
    '',
  ].join('\n\n');
}

// CLI entry: write to dist/theme.css (called by `npm run build:tokens`).
const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const outDir = resolve(dirname(fileURLToPath(import.meta.url)), '../dist');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(resolve(outDir, 'theme.css'), buildThemeCss(), 'utf8');
  console.log('Wrote dist/theme.css');
}
