import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { tokens, themes } from '../src/theme/tokens';

const camelToKebab = (s: string) =>
  s
    // camelCase boundary: lower/digit → Upper (bgDefault → bg-default)
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    // letter → digit boundary: keeps numbered scales readable (chart1 → chart-1)
    .replace(/([a-zA-Z])([0-9])/g, '$1-$2')
    .toLowerCase();

function scaleVars(): string {
  const lines: string[] = [];
  for (const [scaleName, scale] of Object.entries(tokens)) {
    for (const [key, value] of Object.entries(scale)) {
      lines.push(`  --ku-${camelToKebab(scaleName)}-${camelToKebab(String(key))}: ${value};`);
    }
  }
  return lines.join('\n');
}

function colorVars(mode: 'dark' | 'light'): string {
  return Object.entries(themes[mode].color)
    .map(([name, value]) => `  --ku-color-${camelToKebab(name)}: ${value};`)
    .join('\n');
}

export function buildThemeCss(): string {
  return [
    '/* AUTO-GENERATED by scripts/generate-theme-css.ts — do not edit by hand. */',
    `:root {\n${scaleVars()}\n${colorVars('dark')}\n}`,
    `:root[data-theme='dark'], [data-theme="dark"] {\n${colorVars('dark')}\n}`,
    `:root[data-theme='light'], [data-theme="light"] {\n${colorVars('light')}\n}`,
    '',
  ].join('\n\n');
}

// CLI entry: write to dist/theme.css (called by `npm run build:tokens`).
const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const outDir = resolve(dirname(fileURLToPath(import.meta.url)), '../dist');
  mkdirSync(outDir, { recursive: true });
  writeFileSync(resolve(outDir, 'theme.css'), buildThemeCss(), 'utf8');
  console.log('Wrote dist/theme.css');
}
